import { DrawGuessWordEntry } from './draw-guess.types';

export const DRAW_GUESS_WORD_BANK: DrawGuessWordEntry[] = [
  // 动物
  { word: '猫咪', category: '动物' },
  { word: '小狗', category: '动物' },
  { word: '熊猫', category: '动物' },
  { word: '老虎', category: '动物' },
  { word: '狮子', category: '动物' },
  { word: '长颈鹿', category: '动物' },
  { word: '斑马', category: '动物' },
  { word: '河马', category: '动物' },
  { word: '企鹅', category: '动物' },
  { word: '海豚', category: '动物' },
  { word: '鲨鱼', category: '动物' },
  { word: '乌龟', category: '动物' },
  { word: '兔子', category: '动物' },
  { word: '松鼠', category: '动物' },
  { word: '猫头鹰', category: '动物' },
  { word: '孔雀', category: '动物' },
  { word: '蜗牛', category: '动物' },
  { word: '蚂蚁', category: '动物' },
  { word: '蜜蜂', category: '动物' },
  { word: '蝴蝶', category: '动物' },
  { word: '螃蟹', category: '动物' },
  { word: '章鱼', category: '动物' },
  { word: '骆驼', category: '动物' },
  { word: '袋鼠', category: '动物' },
  { word: '狐狸', category: '动物' },
  { word: '恐龙', category: '动物' },

  // 水果
  { word: '苹果', category: '水果' },
  { word: '香蕉', category: '水果' },
  { word: '西瓜', category: '水果' },
  { word: '草莓', category: '水果' },
  { word: '蓝莓', category: '水果' },
  { word: '芒果', category: '水果' },
  { word: '菠萝', category: '水果' },
  { word: '葡萄', category: '水果' },
  { word: '樱桃', category: '水果' },
  { word: '柠檬', category: '水果' },
  { word: '橙子', category: '水果' },
  { word: '榴莲', category: '水果' },
  { word: '桃子', category: '水果' },
  { word: '梨子', category: '水果' },
  { word: '火龙果', category: '水果' },
  { word: '猕猴桃', category: '水果' },
  { word: '山竹', category: '水果' },
  { word: '荔枝', category: '水果' },
  { word: '柚子', category: '水果' },

  // 蔬菜
  { word: '西红柿', category: '蔬菜' },
  { word: '黄瓜', category: '蔬菜' },
  { word: '胡萝卜', category: '蔬菜' },
  { word: '土豆', category: '蔬菜' },
  { word: '茄子', category: '蔬菜' },
  { word: '玉米', category: '蔬菜' },
  { word: '南瓜', category: '蔬菜' },
  { word: '洋葱', category: '蔬菜' },
  { word: '白菜', category: '蔬菜' },
  { word: '西兰花', category: '蔬菜' },
  { word: '菠菜', category: '蔬菜' },
  { word: '豌豆', category: '蔬菜' },
  { word: '蘑菇', category: '蔬菜' },
  { word: '莲藕', category: '蔬菜' },
  { word: '辣椒', category: '蔬菜' },
  { word: '芹菜', category: '蔬菜' },
  { word: '山药', category: '蔬菜' },
  { word: '冬瓜', category: '蔬菜' },

  // 美食
  { word: '火锅', category: '美食' },
  { word: '烧烤', category: '美食' },
  { word: '汉堡', category: '美食' },
  { word: '披萨', category: '美食' },
  { word: '寿司', category: '美食' },
  { word: '拉面', category: '美食' },
  { word: '包子', category: '美食' },
  { word: '饺子', category: '美食' },
  { word: '炸鸡', category: '美食' },
  { word: '蛋糕', category: '美食' },
  { word: '冰淇淋', category: '美食' },
  { word: '麻辣烫', category: '美食' },
  { word: '炒饭', category: '美食' },
  { word: '面包', category: '美食' },
  { word: '三明治', category: '美食' },
  { word: '牛排', category: '美食' },
  { word: '烤鱼', category: '美食' },
  { word: '小笼包', category: '美食' },
  { word: '蛋挞', category: '美食' },
  { word: '煎蛋', category: '美食' },

  // 交通工具
  { word: '自行车', category: '交通工具' },
  { word: '电动车', category: '交通工具' },
  { word: '摩托车', category: '交通工具' },
  { word: '汽车', category: '交通工具' },
  { word: '公交车', category: '交通工具' },
  { word: '地铁', category: '交通工具' },
  { word: '高铁', category: '交通工具' },
  { word: '火车', category: '交通工具' },
  { word: '飞机', category: '交通工具' },
  { word: '轮船', category: '交通工具' },
  { word: '潜水艇', category: '交通工具' },
  { word: '热气球', category: '交通工具' },
  { word: '直升机', category: '交通工具' },
  { word: '火箭', category: '交通工具' },
  { word: '滑板', category: '交通工具' },
  { word: '校车', category: '交通工具' },
  { word: '出租车', category: '交通工具' },
  { word: '救护车', category: '交通工具' },
  { word: '消防车', category: '交通工具' },
  { word: '挖掘机', category: '交通工具' },

  // 日用品
  { word: '牙刷', category: '日用品' },
  { word: '雨伞', category: '日用品' },
  { word: '水杯', category: '日用品' },
  { word: '毛巾', category: '日用品' },
  { word: '枕头', category: '日用品' },
  { word: '被子', category: '日用品' },
  { word: '台灯', category: '日用品' },
  { word: '闹钟', category: '日用品' },
  { word: '书包', category: '日用品' },
  { word: '眼镜', category: '日用品' },
  { word: '拖鞋', category: '日用品' },
  { word: '吹风机', category: '日用品' },
  { word: '镜子', category: '日用品' },
  { word: '肥皂', category: '日用品' },
  { word: '洗发水', category: '日用品' },
  { word: '扫把', category: '日用品' },
  { word: '垃圾桶', category: '日用品' },
  { word: '钥匙', category: '日用品' },
  { word: '手电筒', category: '日用品' },
  { word: '饭盒', category: '日用品' },

  // 家电
  { word: '冰箱', category: '家电' },
  { word: '空调', category: '家电' },
  { word: '电视机', category: '家电' },
  { word: '电饭煲', category: '家电' },
  { word: '微波炉', category: '家电' },
  { word: '烤箱', category: '家电' },
  { word: '电磁炉', category: '家电' },
  { word: '加湿器', category: '家电' },
  { word: '吸尘器', category: '家电' },
  { word: '榨汁机', category: '家电' },
  { word: '咖啡机', category: '家电' },
  { word: '净水器', category: '家电' },
  { word: '电热水壶', category: '家电' },
  { word: '洗衣机', category: '家电' },
  { word: '电风扇', category: '家电' },

  // 乐器
  { word: '钢琴', category: '乐器' },
  { word: '吉他', category: '乐器' },
  { word: '小提琴', category: '乐器' },
  { word: '架子鼓', category: '乐器' },
  { word: '笛子', category: '乐器' },
  { word: '二胡', category: '乐器' },
  { word: '古筝', category: '乐器' },
  { word: '萨克斯', category: '乐器' },
  { word: '口琴', category: '乐器' },
  { word: '琵琶', category: '乐器' },

  // 运动
  { word: '篮球', category: '运动' },
  { word: '足球', category: '运动' },
  { word: '羽毛球', category: '运动' },
  { word: '乒乓球', category: '运动' },
  { word: '网球', category: '运动' },
  { word: '排球', category: '运动' },
  { word: '跳绳', category: '运动' },
  { word: '游泳', category: '运动' },
  { word: '跑步', category: '运动' },
  { word: '瑜伽', category: '运动' },
  { word: '滑雪', category: '运动' },
  { word: '滑冰', category: '运动' },
  { word: '拳击', category: '运动' },
  { word: '举重', category: '运动' },
  { word: '射箭', category: '运动' },
  { word: '攀岩', category: '运动' },

  // 职业
  { word: '医生', category: '职业' },
  { word: '护士', category: '职业' },
  { word: '老师', category: '职业' },
  { word: '警察', category: '职业' },
  { word: '消防员', category: '职业' },
  { word: '厨师', category: '职业' },
  { word: '画家', category: '职业' },
  { word: '程序员', category: '职业' },
  { word: '设计师', category: '职业' },
  { word: '飞行员', category: '职业' },
  { word: '记者', category: '职业' },
  { word: '摄影师', category: '职业' },
  { word: '快递员', category: '职业' },
  { word: '司机', category: '职业' },
  { word: '农民', category: '职业' },
  { word: '工程师', category: '职业' },

  // 自然
  { word: '彩虹', category: '自然' },
  { word: '太阳', category: '自然' },
  { word: '月亮', category: '自然' },
  { word: '星星', category: '自然' },
  { word: '云朵', category: '自然' },
  { word: '雪花', category: '自然' },
  { word: '雷电', category: '自然' },
  { word: '龙卷风', category: '自然' },
  { word: '沙漠', category: '自然' },
  { word: '森林', category: '自然' },
  { word: '海洋', category: '自然' },
  { word: '火山', category: '自然' },
  { word: '瀑布', category: '自然' },
  { word: '湖泊', category: '自然' },
  { word: '冰川', category: '自然' },
  { word: '珊瑚', category: '自然' },

  // 植物
  { word: '向日葵', category: '植物' },
  { word: '玫瑰', category: '植物' },
  { word: '仙人掌', category: '植物' },
  { word: '竹子', category: '植物' },
  { word: '松树', category: '植物' },
  { word: '柳树', category: '植物' },
  { word: '荷花', category: '植物' },
  { word: '梅花', category: '植物' },
  { word: '桃花', category: '植物' },
  { word: '郁金香', category: '植物' },
  { word: '四叶草', category: '植物' },
  { word: '蒲公英', category: '植物' },

  // 场景建筑
  { word: '学校', category: '场景' },
  { word: '医院', category: '场景' },
  { word: '图书馆', category: '场景' },
  { word: '游乐园', category: '场景' },
  { word: '动物园', category: '场景' },
  { word: '博物馆', category: '场景' },
  { word: '电影院', category: '场景' },
  { word: '商场', category: '场景' },
  { word: '超市', category: '场景' },
  { word: '餐厅', category: '场景' },
  { word: '公园', category: '场景' },
  { word: '体育馆', category: '场景' },
  { word: '车站', category: '场景' },
  { word: '机场', category: '场景' },
  { word: '桥梁', category: '场景' },

  // 节日
  { word: '月饼', category: '节日' },
  { word: '春联', category: '节日' },
  { word: '灯笼', category: '节日' },
  { word: '烟花', category: '节日' },
  { word: '粽子', category: '节日' },
  { word: '汤圆', category: '节日' },
  { word: '圣诞树', category: '节日' },
  { word: '礼物', category: '节日' },
  { word: '南瓜灯', category: '节日' },
  { word: '红包', category: '节日' },
  { word: '鞭炮', category: '节日' },

  // 文具与服饰
  { word: '铅笔', category: '文具' },
  { word: '橡皮', category: '文具' },
  { word: '直尺', category: '文具' },
  { word: '剪刀', category: '文具' },
  { word: '胶水', category: '文具' },
  { word: '订书机', category: '文具' },
  { word: '马克笔', category: '文具' },
  { word: '画板', category: '文具' },
  { word: '颜料', category: '文具' },
  { word: '圆规', category: '文具' },
  { word: '帽子', category: '服饰' },
  { word: '围巾', category: '服饰' },
  { word: '手套', category: '服饰' },
  { word: '外套', category: '服饰' },
  { word: '裙子', category: '服饰' },
  { word: '牛仔裤', category: '服饰' },
  { word: '衬衫', category: '服饰' },
  { word: '领带', category: '服饰' },
  { word: '鞋子', category: '服饰' },
];
